CREATE DATABASE BAITHI
GO
USE BAITHI
GO
SET DATEFORMAT DMY

CREATE TABLE NHACUNGCAP
(
	MANCC CHAR(5) NOT NULL,
	PRIMARY KEY(MANCC), 
	TENNCC VARCHAR(40),
	QUOCGIA VARCHAR(50),
	LOAINCC VARCHAR(20)
)

CREATE TABLE DUOCPHAM
(
	MADP CHAR(4) NOT NULL,
	PRIMARY KEY(MADP),
	TENDP VARCHAR(40), 
	LOAIDP VARCHAR(20),
	GIA MONEY
)

CREATE TABLE PHIEUNHAP
(
	SOPN CHAR(5) NOT NULL,
	PRIMARY KEY(SOPN),
	NGNHAP	SMALLDATETIME,
	MANCC	CHAR(5),
	LOAINHAP VARCHAR(20)
)

CREATE TABLE CTPN
(
	SOPN CHAR(5) NOT NULL,
	MADP CHAR(4) NOT NULL,
	PRIMARY KEY(SOPN,MADP),
	SL INT
)


ALTER TABLE PHIEUNHAP
ADD CONSTRAINT FK_PN_NCC FOREIGN KEY(MANCC) REFERENCES NHACUNGCAP(MANCC)
ALTER TABLE CTPN 
ADD CONSTRAINT FK_CTPN_DP FOREIGN KEY(MADP) REFERENCES DUOCPHAM(MADP)
ALTER TABLE CTPN 
ADD CONSTRAINT FK_CTPN_PN FOREIGN KEY(SOPN) REFERENCES PHIEUNHAP(SOPN)


INSERT INTO NHACUNGCAP VALUES('NCC01','Phuc Hung','Viet Nam','Thuong xuyen')
INSERT INTO NHACUNGCAP VALUES('NCC02','J. B. Pharmaceuticals','India','Vang lai')
INSERT INTO NHACUNGCAP VALUES('NCC03','Sapharco','Singapore','Vang lai')

INSERT INTO DUOCPHAM VALUES('DP01','Thuoc ho PH','Siro',120)
INSERT INTO DUOCPHAM VALUES('DP02','Zecuf Herbal CouchRemedy','Vien nen',200)
INSERT INTO DUOCPHAM VALUES('DP03','Cotrim','Vien sui',80)

INSERT INTO PHIEUNHAP VALUES('00001','22/11/2017','NCC01','Noi dia')
INSERT INTO PHIEUNHAP VALUES('00002','04/12/2017','NCC03','Nhap khau')
INSERT INTO PHIEUNHAP VALUES('00003','10/12/2017','NCC02','Nhap khau')

INSERT INTO CTPN VALUES('00001','DP01',100)	
INSERT INTO CTPN VALUES('00001','DP02',200)	
INSERT INTO CTPN VALUES('00003','DP03',543)	

ALTER TABLE DUOCPHAM
ADD CONSTRAINT CHK_LOAIDP_GIA CHECK (LOAIDP = 'Siro' AND GIA > 100)
--CAU 4
--CAU 5
SELECT SOPN FROM PHIEUNHAP WHERE MONTH(NGNHAP) = 12 AND YEAR(NGNHAP) = 2017 ORDER BY NGNHAP ASC
--CAU 6
SELECT TOP 1 WITH TIES MADP 
FROM CTPN,PHIEUNHAP WHERE CTPN.SOPN = PHIEUNHAP.SOPN AND YEAR(NGNHAP) = 2017
ORDER BY SL DESC
--CAU 7
SELECT MADP FROM CTPN WHERE SOPN IN (SELECT SOPN FROM NHACUNGCAP,PHIEUNHAP WHERE LOAINCC = 'Thuong xuyen' AND NHACUNGCAP.MANCC = PHIEUNHAP.MANCC)

--CAU 8
SELECT MANCC FROM PHIEUNHAP WHERE YEAR(NGNHAP) = 2017 AND NOT EXISTS 
(SELECT MADP FROM DUOCPHAM WHERE GIA > 100 AND NOT EXISTS 
(SELECT MADP FROM CTPN WHERE CTPN.SOPN = PHIEUNHAP.SOPN AND CTPN.MADP = DUOCPHAM.MADP))

