CREATE DATABASE DETHISO4
GO
USE DETHISO4
GO
SET DATEFORMAT DMY


CREATE TABLE KHACHHANG
(
	MAKH CHAR(4) NOT NULL,
	PRIMARY KEY(MAKH), 
	TENKH VARCHAR(40),
	DIACHI VARCHAR(50),
	LOAIKH VARCHAR(20),
)

CREATE TABLE LOAICAY
(
	MALC CHAR(4) NOT NULL,
	PRIMARY KEY(MALC),
	TENLC VARCHAR(40),
	XUATXU VARCHAR(20),
	GIA MONEY
)

CREATE TABLE HOADON
(
	SOHD CHAR(5) NOT NULL,
	PRIMARY KEY(SOHD),
	NGHD SMALLDATETIME,
	MAKH CHAR(4),
	KHUYENMAI TINYINT
)

CREATE TABLE CTHD
(
	SOHD CHAR(5) NOT NULL,
	MALC CHAR(4) NOT NULL,
	PRIMARY KEY(SOHD,MALC),
	SOLUONG INT
)
ALTER TABLE HOADON
ADD CONSTRAINT FK_HD_KH FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH)
ALTER TABLE CTHD 
ADD CONSTRAINT FK01_CTHD FOREIGN KEY(SOHD) REFERENCES HOADON(SOHD)
ALTER TABLE CTHD 
ADD CONSTRAINT FK02_CTHD FOREIGN KEY(MALC) REFERENCES LOAICAY(MALC)

INSERT INTO KHACHHANG VALUES('KH01 ','Liz Kim Cuong ','Ha Noi ','Vang lai')
INSERT INTO KHACHHANG VALUES('KH02 ','Ivone Dieu Linh ','Da Nang ','Thuong xuyen')
INSERT INTO KHACHHANG VALUES('KH03 ','Emma Nhat Khanh ','TP.HCM ','Vang lai')

INSERT INTO LOAICAY VALUES('LC01 ','Xuong rong tai tho ','Mexico ','180000')
INSERT INTO LOAICAY VALUES('LC02 ','Sen thach ngoc ','Anh ','300000')
INSERT INTO LOAICAY VALUES('LC03 ','Ba mau rau ','Nam Phi ','270000')

INSERT INTO HOADON VALUES('00001','22/11/2017','KH01',5)
INSERT INTO HOADON VALUES('00002','04/12/2017','KH03',5)
INSERT INTO HOADON VALUES('00003','10/12/2017','KH02',10)

INSERT INTO CTHD VALUES('00001','LC01',1)	
INSERT INTO CTHD VALUES('00001','LC02',2)	
INSERT INTO CTHD VALUES('00003','LC03',5)	
--3
ALTER TABLE LOAICAY
ADD CONSTRAINT CHK_XX_GIA CHECK (XUATXU <> 'Anh' OR GIA > 250000)
--4
CREATE TRIGGER UTG_UD ON HOADON
FOR UPDATE 
AS
BEGIN 
  IF EXISTS (SELECT SUM(SOLUONG),KHUYENMAI
   FROM INSERTED,CTHD 
   WHERE INSERTED.SOHD=CTHD.SOHD AND INSERTED.KHUYENMAI<>10
   GROUP BY KHUYENMAI,INSERTED.SOHD
   HAVING SUM(SOLUONG)>=5)
  BEGIN
     PRINT 'LOI : KHUYEN MAI KHONG THANH CONG!'
	 ROLLBACK TRANSACTION
  END
  ELSE 
  BEGIN
   PRINT 'SUA KHUYEN MAI THANH CONG!'
  END
END


CREATE TRIGGER UTG_UD_INS ON CTHD
FOR INSERT,UPDATE
AS
BEGIN
  IF EXISTS (SELECT * FROM INSERTED,HOADON,CTHD
             WHERE INSERTED.SOHD=CTHD.SOHD AND INSERTED.SOHD=HOADON.SOHD AND KHUYENMAI<>10
			 GROUP BY INSERTED.SOHD
			 HAVING (SUM(CTHD.SOLUONG)) >=5)
 BEGIN 
     PRINT 'LOI'
	 ROLLBACK TRANSACTION
 END
 ELSE
 BEGIN
    PRINT 'THANH CONG!'
 END
END
--5
SELECT SOHD FROM HOADON WHERE (MONTH(NGHD) BETWEEN 10 AND 12) AND YEAR(NGHD) = 2017 ORDER BY KHUYENMAI ASC
--CAU 6
SELECT TOP 1 WITH TIES MALC 
FROM HOADON,CTHD WHERE CTHD.SOHD = HOADON.SOHD AND MONTH(NGHD) = 12
ORDER BY SOLUONG ASC
--7
SELECT MALC FROM CTHD,HOADON,KHACHHANG WHERE CTHD.SOHD = HOADON.SOHD AND KHACHHANG.MAKH=HOADON.MAKH AND LOAIKH='THUONG XUYEN'
INTERSECT 
SELECT MALC FROM CTHD,HOADON,KHACHHANG WHERE CTHD.SOHD = HOADON.SOHD AND KHACHHANG.MAKH=HOADON.MAKH AND LOAIKH='VANG LAI'
--8.
SELECT MAKH FROM HOADON WHERE NOT EXISTS 
(SELECT MALC FROM LOAICAY WHERE NOT EXISTS 
(SELECT MALC FROM CTHD WHERE CTHD.SOHD = HOADON.SOHD AND CTHD.MALC = LOAICAY.MALC))
