CREATE DATABASE BAITHI
GO
USE BAITHI
GO
SET DATEFORMAT DMY

CREATE TABLE HANGHANGKHONG
(
	MAHANG CHAR(2) NOT NULL,
	PRIMARY KEY(MAHANG), 
	TENHANG VARCHAR(40),
	NGTL DATETIME,
	DUONGBAY INT
)

CREATE TABLE CHUYENBAY
(
	MACB CHAR(5) NOT NULL,
	PRIMARY KEY(MACB),
	MAHANG CHAR(2),
	XUATPHAT VARCHAR(40), 
	DIEMDEN VARCHAR(20),
	BATDAU DATETIME,
	TGBAY INT
)

CREATE TABLE NHANVIEN
(
	MANV CHAR(4) NOT NULL,
	PRIMARY KEY(MANV),
	HOTEN VARCHAR(40), 
	GIOITINH VARCHAR(10),
	NGSINH DATETIME,
	
	NGVL DATETIME,
	CHUYENMON VARCHAR(20)
)


CREATE TABLE PHANCONG
(
	MACB CHAR(5) NOT NULL,
	MANV CHAR(4) NOT NULL,
	PRIMARY KEY(MACB,MANV),
	NHIEMVU VARCHAR(20)
)

INSERT INTO HANGHANGKHONG VALUES('VN','Vietnam Airlines','15/01/1956',52)
INSERT INTO HANGHANGKHONG VALUES('VJ','Vietjet Air','25/12/2011',33)
INSERT INTO HANGHANGKHONG VALUES('BL','Jetstar Pacific Airlines','01/12/1990',13)

INSERT INTO CHUYENBAY VALUES('VN550','VN','TP. HCM','Singapore','20/12/2015 13:15:00',2)
INSERT INTO CHUYENBAY VALUES('VJ331','VJ','Đà Nẵng','Vinh','28/12/2015 22:30:00',1)
INSERT INTO CHUYENBAY VALUES('BL696','BL','TP. HCM','Đà Lạt','24/12/2015 06:00:00',0.5)

INSERT INTO NHANVIEN VALUES('NV01','Lâm Văn Bền','Nam','10/09/1978 00:00:00','05/06/2000 00:00:00','Phi công')
INSERT INTO NHANVIEN VALUES('NV02','Dương Thị Lục','Nữ','22/03/1989 00:00:00','12/11/2013 00:00:00','Tiếp viên')
INSERT INTO NHANVIEN VALUES('NV03','Hoàng Thanh Tùng','Nam','29/07/1983 00:00:00','11/04/2007 00:00:00','Tiếp viên')

INSERT INTO PHANCONG VALUES('VN550','NV01','Cơ trưởng')
INSERT INTO PHANCONG VALUES('VN550','NV02','Tiếp viên')
INSERT INTO PHANCONG VALUES('BL696','NV03','Tiếp viên trưởng')

ALTER TABLE CHUYENBAY
ADD CONSTRAINT FK_01 FOREIGN KEY(MAHANG) REFERENCES HANGHANGKHONG(MAHANG)
ALTER TABLE PHANCONG
ADD CONSTRAINT FK_02 FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)
ALTER TABLE PHANCONG
ADD CONSTRAINT FK_03 FOREIGN KEY(MACB) REFERENCES CHUYENBAY(MACB)
--3
ALTER TABLE NHANVIEN
ADD CONSTRAINT CHK_01 CHECK (CHUYENMON IN ('Phi Cong','Tiep Vien'))

--4 
CREATE TRIGGER KT_UD ON HANGHANGKHONG 
FOR  UPDATE
AS
BEGIN
   IF EXISTS( SELECT * FROM INSERTED,HANGHANGKHONG,CHUYENBAY
   WHERE INSERTED.MAHANG=HANGHANGKHONG.MAHANG AND CHUYENBAY.MAHANG=INSERTED.MAHANG AND (GETDATE() - INSERTED.NGTL) < (GETDATE()- CHUYENBAY.BATDAU) )
   BEGIN
    PRINT 'LOI:KHONG DUNG'
	ROLLBACK TRANSACTION
   END
   ELSE 
   BEGIN
   PRINT 'SUA THANH CONG'
   END
END


CREATE TRIGGER KT_UD_IS ON CHUYENBAY
FOR INSERT,UPDATE
AS
BEGIN
  IF EXISTS(SELECT * FROM INSERTED,HANGHANGKHONG,CHUYENBAY
  WHERE INSERTED.MAHANG=HANGHANGKHONG.MAHANG AND CHUYENBAY.MAHANG=INSERTED.MAHANG AND (GETDATE() - INSERTED.BATDAU) > (GETDATE()- HANGHANGKHONG.NGTL) )
  BEGIN
  PRINT 'LOI'
  ROLLBACK TRANSACTION
  END
  ELSE
  BEGIN
  PRINT 'THANH CONG'
  END
END


--5
SELECT * FROM NHANVIEN WHERE MONTH(NGSINH) = 7 

--6
SELECT TOP 1 WITH TIES PHANCONG.MACB
FROM PHANCONG,CHUYENBAY
WHERE PHANCONG.MACB = CHUYENBAY.MACB
ORDER BY COUNT(MANV) DESC

--7
SELECT CHUYENBAY.MACB FROM CHUYENBAY,PHANCONG 
WHERE CHUYENBAY.MACB = PHANCONG.MACB AND XUATPHAT = 'Đà Nẵng'
GROUP BY CHUYENBAY.MACB,PHANCONG.MANV
HAVING (COUNT(MANV) > 2)
--8
SELECT MANV FROM NHANVIEN WHERE NOT EXISTS 
(SELECT MACB FROM CHUYENBAY WHERE NOT EXISTS 
(SELECT * FROM PHANCONG WHERE PHANCONG.MACB = CHUYENBAY.MACB AND PHANCONG.MANV = NHANVIEN.MANV))