CREATE DATABASE TESTDETHI
GO
USE TESTDETHI
GO
SET DATEFORMAT DMY

CREATE TABLE KHACHHANG
(
	MAKH CHAR(4) NOT NULL,
	PRIMARY KEY(MAKH), 
	TENKH VARCHAR(40),
	DIACHI VARCHAR(50),
	LOAIKH VARCHAR(20),
)

CREATE TABLE MATHANG
(
	MAHANG CHAR(4) NOT NULL,
	PRIMARY KEY(MAHANG),
	TENMH VARCHAR(40),
	XUATXU VARCHAR(20),
	GIA MONEY
)

CREATE TABLE HOADON
(
	SOHD CHAR(5) NOT NULL,
	PRIMARY KEY(SOHD),
	NGHD SMALLDATETIME,
	MAKH CHAR(4),
	GIAMGIA INT
)

CREATE TABLE CTHD
(
	SOHD CHAR(5) NOT NULL,
	MAHANG CHAR(4) NOT NULL,
	PRIMARY KEY(SOHD,MAHANG),
	SOLUONG INT
)

ALTER TABLE HOADON
ADD CONSTRAINT FK_HD_KH FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH)
ALTER TABLE CTHD 
ADD CONSTRAINT FK01_CTHD FOREIGN KEY(SOHD) REFERENCES HOADON(SOHD)
ALTER TABLE CTHD 
ADD CONSTRAINT FK02_CTHD FOREIGN KEY(MAHANG) REFERENCES MATHANG(MAHANG)

INSERT INTO KHACHHANG VALUES('KH01','Santa Claus','North Pole','VIP')
INSERT INTO KHACHHANG VALUES('KH02','Rudolph Reindeer','Alaska','Normal')
INSERT INTO KHACHHANG VALUES('KH03','Elsa','Sweden','Normal')


INSERT INTO MATHANG VALUES('MH01','Cay thong Noel','My',680)
INSERT INTO MATHANG VALUES('MH02','Nguoi tuyet bang xop','Viet Nam',500)
INSERT INTO MATHANG VALUES('MH03','Day den chop sang','Trung Quoc',240)

INSERT INTO HOADON VALUES('1','22/10/2020','KH01',10)
INSERT INTO HOADON VALUES('2','04/11/2020','KH03',5)
INSERT INTO HOADON VALUES('3','10/11/2020','KH02',2)

INSERT INTO CTHD VALUES('1','MH01',1)	
INSERT INTO CTHD VALUES('1','MH02',2)	
INSERT INTO CTHD VALUES('3','MH03',5)	

--CAU3
ALTER TABLE MATHANG
ADD CONSTRAINT CHK_XX_GIA CHECK (XUATXU <> 'My' OR GIA > 500000)
--CAU4
UPDATE HOADON
SET GIAMGIA = 8
WHERE MAKH = 'KH01'
CREATE TRIGGER UTG_UD ON HOADON
FOR UPDATE 
AS
BEGIN 
  IF EXISTS (SELECT LOAIKH,GIAMGIA
   FROM INSERTED,KHACHHANG
   WHERE INSERTED.MAKH= KHACHHANG.MAKH AND INSERTED.GIAMGIA < 10
   GROUP BY GIAMGIA
   HAVING LOAIKH = 'VIP')
  BEGIN
     PRINT 'LOI : KHUYEN MAI KHONG THANH CONG!'
	 ROLLBACK TRANSACTION
  END
  ELSE 
  BEGIN
   PRINT 'SUA KHUYEN MAI THANH CONG!'
  END
END


CREATE TRIGGER UTG_UD_INS ON KHACHHANG
FOR UPDATE
AS
BEGIN
  IF EXISTS (SELECT * FROM INSERTED,HOADON
             WHERE INSERTED.MAHANG=HOADON.MAHANG AND GIAMGIA < 10
			 GROUP BY INSERTED.MAHANG
			 HAVING LOAIKH = 'VIP') 
 BEGIN 
     PRINT 'LOI'
	 ROLLBACK TRANSACTION
 END
 ELSE
 BEGIN
    PRINT 'THANH CONG!'
 END
END
--cau5
SELECT SOHD FROM HOADON WHERE MONTH(NGHD) = 11 AND YEAR(NGHD) = 2020 ORDER BY GIAMGIA ASC
--CAU6
SELECT TOP 1 WITH TIES MAHANG
FROM HOADON,CTHD WHERE CTHD.SOHD = HOADON.SOHD AND YEAR(NGHD) = 2020
ORDER BY SOLUONG DESC
--CAU7
SELECT MAHANG FROM CTHD,HOADON,KHACHHANG WHERE CTHD.SOHD = HOADON.SOHD AND KHACHHANG.MAKH=HOADON.MAKH AND LOAIKH='VIP'
EXCEPT
SELECT MAHANG FROM CTHD,HOADON,KHACHHANG WHERE CTHD.SOHD = HOADON.SOHD AND KHACHHANG.MAKH=HOADON.MAKH AND LOAIKH='Normal'
--CAU8
SELECT MAKH FROM HOADON WHERE YEAR(NGHD) = 2020 AND NOT EXISTS 
(SELECT MAHANG FROM MATHANG WHERE XUATXU = 'Viet Nam' AND  NOT EXISTS 
(SELECT MAHANG FROM CTHD WHERE CTHD.SOHD = HOADON.SOHD AND CTHD.MAHANG = MATHANG.MAHANG))
SELECT * FROM HOADON AS B1 WHERE YEAR(NGHD)=2020 AND NOT EXISTS(
SELECT * FROM MATHANG WHERE XUATXU='VIET NAM' AND NOT EXISTS(
SELECT * FROM HOADON,CTHD WHERE HOADON.SOHD=CTHD.SOHD AND HOADON.SOHD=B1.SOHD AND CTHD.MAHANG=MATHANG.MAHANG))